<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2022-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Checkout\Model\Form\AbstractEntityFormElement;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Escaper $escaper */
/** @var Template $block */

/** @var AbstractEntityFormElement $element */
$element = $block->getData('element');
?>
<?php if ($element->hasComment()): ?>
    <p class="mt-4 font-normal text-slate-700">
        <?= $escaper->escapeHtml(__($element->getComment())) ?>
    </p>
<?php endif ?>
