<?php declare(strict_types=1);
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */
use Hdweb\Vehicles\Block\Checkout\Registration;
//use Magento\Checkout\Block\Registration;
use Magento\Framework\Escaper;

/** @var Registration $block */
/** @var Escaper $escaper */
?>
<?php if(!$block->isCustomerLoggedIn()){ ?>
<div class="sucess-register mt-3 md:mt-0 bg-white rounded-[10px] border-b-[6px] border-b-theme-blue border border-[#D9D9D9] shadow-lg lg:h-auto overflow-hidden px-5 md:px-8 pt-4 md:pt-6 pb-3 md:pb-4 w-full md:w-1/2 lg:w-2/5 xl:w-1/4">
    <p class="text-base md:text-lg text-theme-dark"><?= $escaper->escapeHtml(__('You can track your order status by creating an account.')) ?></p>
    <p class="text-base md:text-lg text-theme-dark"><?= $escaper->escapeHtml(__('Email Address:')) ?> <?= $escaper->escapeHtml($block->getEmailAddress()) ?></p>
    <div class="mt-4 text-center">
        <a class="btn btn-primary inline-block" href="<?= $escaper->escapeUrl($block->getCreateAccountUrl()) ?>">
            <span><?= $escaper->escapeHtml(__('Create an Account')) ?></span>
        </a>
    </div>
</div>
<?php } ?>
