<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Checkout\Block\Onepage\Success;

/** @var Success $block */
/** @var Escaper $escaper */
?>
<div class="checkout-success bg-white rounded-[10px] border-b-[6px] border-b-theme-blue border border-[#D9D9D9] shadow-lg lg:h-auto overflow-hidden px-5 md:px-8 pt-4 md:pt-6 pb-3 md:pb-4 w-full md:w-1/2 lg:w-2/5 xl:w-1/4"">
    <?php if ($block->getOrderId()): ?>
        <?php if ($block->getCanViewOrder()): ?>
            <p class="text-base md:text-lg text-theme-dark font-semibold">
                <?= $escaper->escapeHtml(
                    __(
                        'Your order number is: %1.',
                        sprintf(
                            '<a href="%s" class="order-number"><strong>%s</strong></a>',
                            $escaper->escapeUrl($block->getViewOrderUrl()),
                            $block->getOrderId()
                        )
                    ),
                    ['a', 'strong']
                ) ?>
            </p>
        <?php  else: ?>
            <p class="text-base md:text-lg text-theme-dark font-semibold"><?= $escaper->escapeHtml(__('Your order # is: <span>%1</span>.', $block->getOrderId()), ['span']) ?></p>
        <?php endif;?>
        <p class="text-base md:text-lg text-theme-dark">
            <?= $escaper->escapeHtml(
                __('We\'ll email you an order confirmation with details and tracking info.')
            ) ?>
        </p>
    <?php endif; ?>

    <?= $block->getAdditionalInfoHtml() ?>

    <div class="mt-4 text-center">
        <a class="btn btn-primary inline-flex" href="<?= $escaper->escapeUrl($block->getContinueUrl()) ?>">
            <span><?= $escaper->escapeHtml(__('Continue Shopping')) ?></span>
        </a>
    </div>
</div>

