<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Magento\Customer\Block\Address\Book;
use Magento\Framework\Escaper;

/** @var Book $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);
?>
<div class="block block-addresses-default">
    <h2 class="mb-4 text-xl block-title">
            <?= $escaper->escapeHtml(__('Default Addresses')) ?>
    </h2>
    <div class="grid-cols-2 block-content md:grid gap-x-4 gap-y-0 my-6">
        <?php if ($customerDefaultBillingAddressId = $block->getDefaultBilling()): ?>
            <div class="box box-address-billing bg-white rounded-[10px] border-b-[6px] border-b-black border border-[#D9D9D9] shadow-lg p-[1rem] md:p-[1.7rem] lg:p-[2.2rem] xl:p-[2.5rem]">
                <div class="mb-3 text-lg font-medium text-gray-900 title-font font-semibold">
                    <span><?= $escaper->escapeHtml(__('Default Billing Address')) ?></span>
                </div>
                <div class="box-content">
                    <address>
                        <?= $block->getAddressHtml($block->getAddressById($customerDefaultBillingAddressId)) ?>
                    </address>
                </div>
                <div class="box-actions">
                    <a href="<?= $escaper->escapeUrl($block->getAddressEditUrl($customerDefaultBillingAddressId)) ?>"
                       class="inline-flex items-center w-full mt-3 md:text-sm text-secondary
                        hover:text-secondary-darker"
                       >
                        <span>
                            <?= $escaper->escapeHtml(__('Change Billing Address')) ?>
                        </span>
                        <?= $heroicons->arrowRightHtml('ml-2', 16, 16); ?>
                    </a>
                </div>
            </div>
        <?php else: ?>
            <div class="box box-billing-address bg-white rounded-[10px] border-b-[6px] border-b-black border border-[#D9D9D9] shadow-lg p-[1rem] md:p-[1.7rem] lg:p-[2.2rem] xl:p-[2.5rem]">
                <div class="mb-3 text-lg font-medium text-gray-900 title-font font-semibold">
                    <span>
                        <?= $escaper->escapeHtml(__('Default Billing Address')) ?>
                    </span>
                </div>
                <div class="box-content">
                    <p><?= $escaper->escapeHtml(__('You have no default billing address in your address book.')) ?></p>
                </div>
            </div>
        <?php endif ?>

        <?php if ($customerDefaultShippingAddressId = $block->getDefaultShipping()): ?>
            <div class="mt-3 lg:mt-0 box box-address-shipping bg-white rounded-[10px] border-b-[6px] border-b-black border border-[#D9D9D9] shadow-lg p-[1rem] md:p-[1.7rem] lg:p-[2.2rem] xl:p-[2.5rem]">
                <div class="mb-3 text-lg font-medium text-gray-900 title-font font-semibold">
                    <span><?= $escaper->escapeHtml(__('Default Shipping Address')) ?></span>
                </div>
                <div class="box-content">
                    <address>
                        <?= $block->getAddressHtml($block->getAddressById($customerDefaultShippingAddressId)) ?>
                    </address>
                </div>
                <div class="box-actions">
                    <a href="<?= $escaper->escapeUrl($block->getAddressEditUrl($customerDefaultShippingAddressId)) ?>"
                       class="inline-flex items-center w-full mt-3 md:text-sm text-secondary
                        hover:text-secondary-darker"
                    >
                        <span><?= $escaper->escapeHtml(__('Change Shipping Address')) ?></span>
                        <?= $heroicons->arrowRightHtml('ml-2', 16, 16); ?>
                    </a>
                </div>
            </div>
        <?php else: ?>
            <div class="mt-3 lg:mt-0 box box-shipping-address bg-white rounded-[10px] border-b-[6px] border-b-black border border-[#D9D9D9] shadow-lg p-[1rem] md:p-[1.7rem] lg:p-[2.2rem] xl:p-[2.5rem]">
                <div class="mb-3 text-lg font-medium text-gray-900 title-font font-semibold">
                    <span>
                        <?= $escaper->escapeHtml(__('Default Shipping Address')) ?>
                    </span>
                </div>
                <div class="box-content">
                    <p>
                        <?= $escaper->escapeHtml(__('You have no default shipping address in your address book.')) ?>
                    </p>
                </div>
            </div>
        <?php endif ?>
    </div>
</div>
