<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2022-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Checkout\ViewModel\Checkout\Formatter as FormatterViewModel;
use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Magento\Tax\Model\Config as TaxConfig;

/** @var Template $block */
/** @var FormatterViewModel $formatterViewModel */
/** @var ViewModelRegistry $viewModels */
/** @var Escaper $escaper */
/** @var TaxConfig $taxConfig */

$formatterViewModel = $viewModels->require(FormatterViewModel::class);
$segments = $block->getSegment();
$taxConfig = $block->getTaxConfig();
$label = $block->getParentBlock()->getSegment()['title'] ?? 'Grand Total';
?>

<?php if ($segments && $taxConfig->displayCartTaxWithGrandTotal()): ?>
    <?php foreach ($segments as $item): ?>
        <div class="flex gap-4 justify-between md:gap-0">
            <span class="label">
                <?= $escaper->escapeHtml(__('%1 Excl. Tax', $label)) ?>
            </span>

            <span class="value text-right">
                <?= /* @noEscape */ $formatterViewModel->currency($item->getExclTaxValue()) ?>
            </span>
        </div>
    <?php endforeach ?>
<?php endif ?>
