<?php

/**
 * @category   Hdweb
 * @package    Hdweb_Vehicles
 * @author     vicky.hdit@gmail.com
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace Hdweb\Vehicles\Controller\Adminhtml\Items;

class GetModels extends \Hdweb\Vehicles\Controller\Adminhtml\Items
{
    /**
     * Items list.
     *
     * @return \Magento\Backend\Model\View\Result\Page
     */
    public function execute()
    {
        $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
        $resultJsonFactory = $objectManager->get('\Magento\Framework\Controller\Result\JsonFactory');
        $make = $this->getRequest()->getParam('make');

        // Old: External API call to Klever/wheel-size
        // $wheelApiKey = '49431246078dcbff7a9d65b50471413c4114304a90672922de02014ba0ce9eb9';
        // $VehicleModel_url = "https://wheel-api.klever.ae/v1/models/?user_key=" . $wheelApiKey . "&make=" . $make . "&region=medm";
        // $WheelVehicleModel = file_get_contents($VehicleModel_url);
        // if(empty($WheelVehicleModel)) {
        //     $wheelApiKey = $objectManager->get('Magento\Framework\App\Config\ScopeConfigInterface')->getValue('hdwebapi/general/wheelsize_api_key');
        //     $VehicleModel_url = "https://api.wheel-size.com/v2/models/?user_key=" . $wheelApiKey . "&make=" . $make . "&region=medm";
        //     $WheelVehicleModel = file_get_contents($VehicleModel_url);
        // }
        // $WheelVehicleModel = json_decode($WheelVehicleModel);

        // New: Read from Klever VehicleTyresGuide flat_wheel_data table
        $flatWheelData = $objectManager->get(\Klever\VehicleTyresGuide\Model\ResourceModel\FlatWheelData::class);
        $result = $flatWheelData->getModels($make, ['ordering' => 'name']);

        $html = '<option value="">Select Model</option>';
        foreach ($result['rows'] as $modelOption) {
            $html .= '<option value="' . $modelOption['slug'] . '">' . $modelOption['name'] . '</option>';
        }

        $response['response'] = $html;
        $resultJson = $resultJsonFactory->create();
        return $resultJson->setData($response);
    }
}
