<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);
/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Magento\Framework\Escaper $escaper */

?>
<div class="p-3 md:py-5 lg:py-8 text-center bg-[#FAFAFA] border border-[#D9D9D9] my-4 md:my-5">
    <p class="text-[1.1rem] md:text-[1.2rem] lg:text-[1.2rem] xl:text-[1.4rem] font-semibold">
        <?= $escaper->escapeHtml(__('You have signed out and will be redirected to our homepage in 5 seconds.')) ?>
    </p>
    <p class="mt-1 md:mt-3">
        <?= $escaper->escapeHtml(__('Thank you for your visit, we\'re looking forward to see you again soon.')) ?>
    </p>
</div>
<script>
     setTimeout(function() {
        location.href = "<?= $escaper->escapeJs($escaper->escapeUrl($block->getUrl())) ?>"
    }, 5000); 
</script>
