<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Magento\Customer\Block\Form\Login\Info;
use Magento\Framework\Escaper;

/** @var Info $block */
/** @var Escaper $escaper */
?>
<?php if ($block->getRegistration()->isAllowed()): ?>
   <div class="block-new-customer bg-white rounded-[10px] border-b-[6px] border-b-black border border-[#D9D9D9] shadow-lg p-[1rem] md:p-[1.7rem] lg:p-[2.2rem] xl:p-[2.5rem] w-full xl:w-1/3">
        <div class="block-title">
            <h2 class="text-xl title-font mb-3 text-primary font-semibold" role="heading"
                aria-level="2"><?= $escaper->escapeHtml(__('New Customers')) ?></h2>
        </div>
        <div class="block-content" aria-labelledby="block-new-customer-heading">
            <p class="text-secondary-darker">
                <?= $escaper->escapeHtml( // phpcs:disable Generic.Files.LineLength.TooLong
                    __('Creating an account has many benefits: check out faster, keep more than one address, track orders and more.')
                ) // phpcs:enable ?>
            </p>
        </div>
        <div class="actions-toolbar pt-6 pb-2">
            <a href="<?= $escaper->escapeUrl($block->getCreateAccountUrl()) ?>"
               class="btn bg-black text-white text-[0.9rem] md:text-[1rem] hover:bg-theme-blue transition-all duration-300 ease-in-out disabled:opacity-75"><span><?= $escaper->escapeHtml(__('Create an Account')) ?></span></a>
        </div>
    </div>
<?php endif; ?>
