<?php
$configHelper = $this->helper('MGS\Ajaxlayernavigation\Helper\Config');
$params = $block->getRequest()->getParams();
?>

<?php /* $_filters = $block->getAppliedFilters(); Magento < 2.4.1 */ ?>
<?php $_filters = $block->getActiveFilters() // Magento 2.4.1+ ?>
<div id="filter-container" <?php if ($configHelper->removeShoppingBy()): ?> style="display:none !important" <?php endif ?>>
	<?php if (!empty($_filters)): ?>
		<?php
		$_state = [];
		foreach ($_filters as $_filter) {
			$filterName = $_filter->getName();
			if (is_object($filterName)) {
				$filterName = $filterName->getText();
			}
			$_state[$filterName][] = [
				"label" => $_filter->getLabel(),
				"url" => $_filter->getRemoveUrl()
			];
		}
		?>
		<div class="filter-active mgs-filter-active">
			<strong class="block-subtitle filter-current-subtitle"><?php echo __('Now Shopping by') ?></strong>
			<?php
			$width = '';
			$height = '';
			$rim = '';
			$sizeLabel = '';
			?>
			<?php foreach ($_state as $_filterName => $_items): ?>
				<span class="shoppingby-item <?php echo strtolower($_filterName); ?>">
					<?php foreach ($_items as $_filter): ?>
						<?php
						$label = $block->stripTags($_filter['label']);
						$removeUrl = $_filter['url'];
						if (strtolower($_filterName) == 'width') {
							$width = $label;
						}
						if (strtolower($_filterName) == 'height') {
							$height = $label;
						}
						if (strtolower($_filterName) == 'rim') {
							$sizeLabel = $width . '/' . $height . ' R' . $label;
						}
						if (isset($params['width_rear']) && $params['width_rear'] != '' && isset($params['height_rear']) && $params['height_rear'] != '' && isset($params['rim_rear']) && $params['rim_rear'] != '') {
							$sizeLabel = $sizeLabel . ' - ' . $params['width_rear'] . '/' . $params['height_rear'] . ' R' . $params['rim_rear'];
						}
						?>
						<?php if (strtolower($_filterName) == 'rim'): ?>
							<div class="state-item">
								<a class="filter-active-item-clear-all" title=""
									href="<?php /* @escapeNotVerified */ echo $configHelper->getClearAllUrl() ?>">
									<span><?php /* @escapeNotVerified */ echo $sizeLabel ?></span>
								</a>
							</div>
						<?php else: ?>
							<div class="state-item" onclick="location.href='<?php echo $removeUrl ?>'">
								<span class="state-item-name"
									title="<?php echo $label ?>"><span><?php echo $block->escapeHtml(__($_filterName)); ?>:</span>
									<?php echo $label ?></span>
								<span class="state-item-remove"><span class="state-item-icon-cancel"></span></span>
								<a class="state-item-remove-url" href="<?php echo $removeUrl ?>"></a>
							</div>
						<?php endif; ?>

					<?php endforeach; ?>
				</span>
			<?php endforeach; ?>

			<span class="shoppingby-item" onclick="location.href='<?php echo $configHelper->getClearAllUrl() ?>'">
				<div class="shoppingby-item state-item"><a class="filter-active-item-clear-all"
						title="<?php /* @escapeNotVerified */ echo __('Clear All') ?>"
						href="<?php /* @escapeNotVerified */ echo $configHelper->getClearAllUrl() ?>">
						<span><?php /* @escapeNotVerified */ echo __('Clear All') ?></span></a></div>
			</span>


		</div>
	<?php endif; ?>
</div>

