<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2022-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Checkout\Model\Form\EntityFormInterface;
use Hyva\Checkout\Magewire\Checkout\AddressView\MagewireAddressFormInterface;
use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Directory\Model\Country as CountryModel;
use Magento\Directory\Model\Region as RegionModel;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var ViewModelRegistry $viewModels */
/** @var MagewireAddressFormInterface $magewire */
/** @var CountryModel $country */
/** @var RegionModel $region */
/** @var Escaper $escaper */
/** @var EntityFormInterface $form */

$form = $magewire->getPublicForm();
$namespace = $form->getNamespace();
?>
<div>
    <form
        <?= /* @noEscape */ $form->renderAttributes($escaper) ?>
        class=" address-form"
        x-data="hyvaCheckoutAddressListForm"
        novalidate
        style="padding-left: 0;
        padding-right: 0;"
    >

    <div class="section-title w-full pb-2">
        <div class="flex items-center justify-between p-4 border-b border-border-color relative">
                <h3 class="h4 uppercase text-left w-full">New <span class="text-theme-blue">Address </span></h3>

                 <button
                type="button"
                class="absolute top-0 right-2 p-4 mt-1 text-black transition-colors hover:text-theme-blue"
                x-on:click="cancelForm"
            >
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" width="24" height="24" aria-hidden="true">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12"></path>
                    </svg>
            </button>
            </div>
    </div>


    <div class="bg-white rounded-lg px-4 sm:px-4">
        <div class="grid grid-cols-12 gap-x-3">
            <?= /** @noEscape */ $block->getChildHtml('address-form.before') ?>

            <?php if ($form->hasFields()): ?>
                <?php foreach ($form->getFields() as $field): ?>
                    <?php if ($field->canRender()): ?>
                        <?php /** @purge: md:col-span-3 md:col-span-6 md:col-span-9 md:col-span-12 */ ?>
                        <div class="<?= $escaper->escapeHtmlAttr($field->renderWrapperClass(['col-span-12'])) ?>"
                             <?= /* @noEscape */ $field->renderAttributes($escaper, 'wrapper') ?>
                        >
                            <?= /* @noEscape */ $field->render() ?>

                            <?php if ($magewire->hasError($field->getId())): ?>
                                <?= /** @noEscape */ $magewire->getError($field->getId()) ?>
                            <?php endif ?>
                        </div>
                    <?php endif ?>
                <?php endforeach ?>
            <?php endif ?>

            <?= /** @noEscape */ $block->getChildHtml('address-form.after') ?>
        </div>

        <div class="flex space-x-4 items-center">
            <button
                type="button"
                class="btn btn-primary"
                x-on:click="saveForm"
                wire:loading.attr="disabled"
            >
                <?= $escaper->escapeHtml(__('Save')) ?>
            </button>

            <button
                type="button"
                class="btn btn-secondary"
                x-on:click="cancelForm"
            >
                <?= $escaper->escapeHtml(__('Cancel')) ?>
            </button>
        </div>
       </div> 



    </form>
</div>
