

<section class="py-10 md:py-12 lg:py-14">
   <div class="container-theme mx-auto">
      <div class="error-image relative w-[40%] mx-auto">
                  <div class="img_wrp w-full pb-full h-0 z-0 bg-gray-200 pb-[36%]">
                     <figure class="absolute inset-0">
                        <picture>
                           <source srcset="<?php echo $this->getViewFileUrl('images/pages/page-error.jpg'); ?>" loading="lazy" alt="error" type="image/jpg">
                           <source srcset="<?php echo $this->getViewFileUrl('images/pages/page-error.jpg'); ?>" loading="lazy" alt="error" type="image/jpg">
                           <img class="w-full h-full object-cover object-top" src="<?php echo $this->getViewFileUrl('images/pages/page-error.jpg'); ?>" alt="error" loading="lazy">
                        </picture>
                     </figure>
                  </div>
               </div>

               <div class="error-content">
                  <h2 class="text-[1.5rem] md:text-[1.65rem] lg:text-4xl text-theme-dark font-bold relative pb-3 md:pb-5 mb-3 md:mb-5 flex">
                  Oops! That Page Can Not be Found.
               </h2>
               </div>
   </div>
</section>




















