<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2022-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Checkout\Model\Form\EntityField\AbstractEntityField;
use Hyva\Checkout\Model\Form\EntityFormElement\Renderer\AbstractRenderer;
use Hyva\Checkout\ViewModel\Form\Field as FormFieldViewModel;
use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsSolid;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var ViewModelRegistry $viewModels */
/** @var Escaper $escaper */

/** @var HeroiconsSolid $heroiconsSolid */
$heroiconsSolid = $viewModels->require(HeroiconsSolid::class);

/** @var FormFieldViewModel $formFieldViewModel */
$formFieldViewModel = $viewModels->require(FormFieldViewModel::class);

/** @var AbstractEntityField $element */
$element = $block->getData('element');

// Set input type based on the visibility toggle.
$element->setAttribute('x-bind:type', 'textOrPassword');

// Enforce the input type attribute
$element->setAttribute('type', 'password');

/** @var AbstractRenderer $renderer */
$renderer = $element->getRenderer();

// Additional variables
$cssClassesFieldWrapperInner = $element->renderClass(['field'], 'field-wrapper-inner');
?>
<div x-data="hyvaCheckoutPasswordVisibility"
     class="<?= $escaper->escapeHtmlAttr($cssClassesFieldWrapperInner) ?>"
>
    <?= /* @noEscape */ $renderer->renderLabel($element) ?>
    <?= /* @noEscape */ $renderer->renderBefore($element) ?>

    <?php if ($element->hasRelatives()): ?>
        <div class="space-y-2">
    <?php endif ?>

        <div class="group input-group flex gap-4">
            <?php if ($element->hasIcon()): ?>
                <div class="form-input-addon inline-flex gap-2 items-center">
                    <?= /* @noEscape */ $renderer->renderIcon($element) ?>
                </div>
            <?php endif ?>

            <input
                class="<?= $escaper->escapeHtmlAttr($element->renderClass(['form-input w-full grow'])) ?>"
                <?php if ($element->hasAttributes()): ?>
                    <?= /* @noEscape */ $element->renderAttributes($escaper) ?>
                <?php endif ?>
            >

            <?php if ($formFieldViewModel->designConfig()->showPasswordVisibilityToggle()): ?>
                <div class="form-input-addon inline-flex gap-2 items-center">
                    <button
                        type="button"
                        class="shrink-0"
                        x-on:click="toggleVisible"
                        x-bind:aria-pressed="visible"
                        x-bind:aria-label="ariaLabel"
                    >
                        <template x-if="!visible">
                            <?= $heroiconsSolid->eyeHtml('', 20, 20, ['aria-hidden' => 'true']) ?>
                        </template>

                        <template x-if="visible">
                            <?= $heroiconsSolid->eyeOffHtml('', 20, 20, ['aria-hidden' => 'true']) ?>
                        </template>
                    </button>
                </div>
            <?php endif ?>

            <?php if (!empty($renderer->renderTooltip($element))): ?>
                <div class="form-input-addon inline-flex gap-2 items-center">
                    <?= /* @noEscape */ $renderer->renderTooltip($element) ?>
                </div>
            <?php endif ?>
        </div>
        <?= /* @noEscape */ $renderer->renderHintText($element) ?>
        <?= /* @noEscape */ $renderer->renderComment($element) ?>

        <?php if ($element->hasRelatives()): ?>
            <?php foreach ($element->getRelatives() as $relative): ?>
                <?php if ($relative->isVisible()): ?>
                    <?= /* @noEscape */ $relative->render() ?>
                <?php endif ?>
            <?php endforeach ?>
        <?php endif ?>

    <?php if ($element->hasRelatives()): ?>
        </div>
    <?php endif ?>

    <?= /* @noEscape */ $renderer->renderAfter($element) ?>
</div>
