<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2022-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Checkout\Model\Form\EntityField\AbstractEntityField;
use Hyva\Checkout\Model\Form\EntityFormElement\Renderer\AbstractRenderer;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */

/** @var AbstractEntityField $element */
$element = $block->getData('element');

// Enforce the input type attribute
$element->removeAttribute('type');

/** @var AbstractRenderer $renderer */
$renderer = $element->getRenderer();

// Additional variables
$cssClassesFieldWrapperInner = $element->renderClass(['field'], 'field-wrapper-inner');
?>
<div class="<?= $escaper->escapeHtmlAttr($cssClassesFieldWrapperInner) ?>">
    <?= /* @noEscape */ $element->getRenderer()->renderLabel($element) ?>
    <?= /* @noEscape */ $element->getRenderer()->renderBefore($element) ?>

    <?php if ($element->hasRelatives()): ?>
        <div class="space-y-2">
    <?php endif ?>

    <div class="group input-group flex gap-4">
        <?php if ($element->hasIcon()): ?>
            <div class="form-input-addon inline-flex gap-2 items-center">
                <?= /* @noEscape */ $renderer->renderIcon($element) ?>
            </div>
        <?php endif ?>

        <select
            class="<?= $escaper->escapeHtmlAttr($element->renderClass(['block w-full form-select'])) ?>"
            <?php if ($element->hasAttributes()): ?>
                <?= /* @noEscape */ $element->renderAttributes($escaper) ?>
            <?php endif ?>
        >
            <?php foreach ($element->getOptions() as $key => $option): ?>
                <?php if (is_object($option)): ?>
                    <option value="<?= $escaper->escapeHtmlAttr($option->getValue()) ?>">
                        <?= $escaper->escapeHtml(__($option->getLabel())) ?>
                    </option>
                <?php elseif (is_array($option)): ?>
                    <option value="<?= $escaper->escapeHtmlAttr($option['value']) ?>">
                        <?= $escaper->escapeHtml(__($option['label'])) ?>
                    </option>
                <?php elseif (is_string($option)): ?>
                    <option value="<?= $escaper->escapeHtmlAttr($key) ?>">
                        <?= $escaper->escapeHtml(__($option)) ?>
                    </option>
                <?php endif ?>
            <?php endforeach ?>
        </select>

        <?php if (!empty($renderer->renderTooltip($element))): ?>
            <div class="form-input-addon inline-flex gap-2 items-center">
                <?= /* @noEscape */ $renderer->renderTooltip($element) ?>
            </div>
        <?php endif ?>
    </div>
    <?= /* @noEscape */ $renderer->renderHintText($element) ?>
    <?= /* @noEscape */ $renderer->renderComment($element) ?>

    <?php if ($element->hasRelatives()): ?>
        <?php foreach ($element->getRelatives() as $relative): ?>
            <?php if ($relative->isVisible()): ?>
                <?= /* @noEscape */ $relative->render() ?>
            <?php endif ?>
        <?php endforeach ?>
    <?php endif ?>

    <?php if ($element->hasRelatives()): ?>
        </div>
    <?php endif ?>

    <?= /* @noEscape */ $renderer->renderAfter($element) ?>
</div>
