<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2022-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Checkout\Model\Form\EntityField\AbstractEntityField;
use Hyva\Checkout\Model\Form\EntityFormElement\Renderer\AbstractRenderer;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Escaper $escaper */
/** @var Template $block */

/** @var AbstractEntityField $element */
$element = $block->getData('element');

/** @var AbstractRenderer $renderer */
$renderer = $element->getRenderer();

// Additional variables
$cssClassesFieldWrapperInner = $element->renderClass(['field'], 'field-wrapper-inner')

/** @Tailwind md:w-1/4 md:w-2/4 md:w-3/4 md:w-4/4 mb-2 */
?>
<div class="<?= $escaper->escapeHtmlAttr($cssClassesFieldWrapperInner) ?> Gir">
    <?= /* @noEscape */ $renderer->renderLabel($element) ?>
    <?= /* @noEscape */ $renderer->renderBefore($element) ?>

    <?php if ($element->hasRelatives()): ?>
        <div class="space-y-2">
    <?php endif ?>

    <div class="group input-group flex gap-4">
        <?php if ($element->hasIcon()): ?>
            <div class="form-input-addon inline-flex gap-2 items-center">
                <?= /* @noEscape */ $renderer->renderIcon($element) ?>
            </div>
        <?php endif ?>

        <?php if ($element->getName() == 'telephone'): ?>
                <input class="<?= $escaper->escapeHtmlAttr($element->renderClass(['form-input'])) ?> "
                    placeholder="5XXXXXXXX"
                    style="direction: ltr; text-align: left !important;"
                    <?php if ($element->hasAttributes()): ?>
                    <?= /* @noEscape */ $element->renderAttributes($escaper) ?>
                    <?php endif ?> />
         <?php elseif($element->getName() == 'region'): ?> 
                <input class="<?= $escaper->escapeHtmlAttr($element->renderClass(['form-input'])) ?> " type="text" value="Dubai"  id="shipping-region" name="region" />          
            <?php elseif($element->getName() == 'postcode'): ?> 
               <input class="<?= $escaper->escapeHtmlAttr($element->renderClass(['form-input'])) ?> " type="text" value="01234" data-form="shipping" data-attribute="postcode" data-order="13" data-level="0"  id="shipping-postcode" name="postcode" autocomplete="postal-code" data-attribute-address="true" data-magewire-is-valid="1" data-validate="{&quot;magewire&quot;:true}" wire:loading.class="loading" wire:loading.attr="disabled" wire:target="postcode" wire:auto-save="shipping" wire:model.defer="address.postcode">
        <?php else: ?>

            <input
                class="<?= $escaper->escapeHtmlAttr($element->renderClass(['form-input w-full grow'])) ?> <?php echo $element->getName();?>"
                <?php if ($element->hasAttributes()): ?>
                    <?= /* @noEscape */ $element->renderAttributes($escaper) ?>
                <?php endif ?>
            >
        <?php endif ?>

        <?php if (!empty($renderer->renderTooltip($element))): ?>
            <div class="form-input-addon inline-flex gap-2 items-center">
                <?= /* @noEscape */ $renderer->renderTooltip($element) ?>
            </div>
        <?php endif ?>
    </div>
    <?= /* @noEscape */ $renderer->renderHintText($element) ?>
    <?= /* @noEscape */ $renderer->renderComment($element) ?>

    <?php if ($element->hasRelatives()): ?>
        <?php foreach ($element->getRelatives() as $relative): ?>
            <?php if ($relative->isVisible()): ?>
                <?= /* @noEscape */ $relative->render() ?>
            <?php endif ?>
        <?php endforeach ?>
    <?php endif ?>

    <?php if ($element->hasRelatives()): ?>
        </div>
    <?php endif ?>

    <?= /* @noEscape */ $renderer->renderAfter($element) ?>
</div>
