<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

/**
 * The AlpineJS scope of this file is the method `initCartTotals()` in Magento_Checkout::php-cart/totals.phtml
 */
?>
<template x-if="segment.code === 'discount'">
    <div class="flex px-4 pb-2 my-2 border-b border-slate-300 text-base md:text-lg md:grid md:grid-cols-2 md:w-full border-container">
        <div class="w-7/12 text-right md:w-auto"
             x-html="segment.title"
        ></div>
        <div class="w-5/12 text-left md:w-auto font-semibold price"
             x-html="hyva.formatPrice(segment.value)"
        ></div>
    </div>
</template>
