<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

// phpcs:disable Magento2.Templates.ThisInTemplate

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\Cart\ItemOutput;
use Hyva\Theme\ViewModel\Modal;
use Magento\Checkout\Block\Cart\Grid;
use Magento\Checkout\ViewModel\Cart as CartViewModel;
use Magento\Framework\Escaper;

/** @var Grid $block */
/** @var ViewModelRegistry $viewModels */
/** @var Escaper $escaper */

/** @var CartViewModel $cartViewModel */
$cartViewModel = $viewModels->require(CartViewModel::class);

/** @var Modal $modalViewModel */
$modalViewModel = $viewModels->require(Modal::class);

/** @var ItemOutput $cartItemOutputViewModel */
$cartItemOutputViewModel = $viewModels->require(ItemOutput::class);
?>
<?php $mergedCells = ($cartItemOutputViewModel->isItemPriceDisplayBoth() ? 2 : 1); ?>
<?= $block->getChildHtml('form_before') ?>
<form action="<?= $escaper->escapeUrl($block->getUrl('checkout/cart/updatePost')) ?>"
      x-data="{}"
      @submit.prevent="hyva.postCart($event.target)"
      method="post"
      id="form-validate"
      class="form form-cart"
>
    <?= $block->getBlockHtml('formkey') ?>
    <div class="cart bg-white rounded-[10px] border-b-[6px] border-b-black border border-[#D9D9D9] shadow-lg w-full lg:h-auto overflow-hidden table-wrapper<?= $mergedCells == 2 ? ' detailed' : '' ?>">
        <?php if ($block->getPagerHtml()): ?>
            <div class="cart-products-toolbar cart-products-toolbar-top toolbar">
                <?= $block->getPagerHtml() ?>
            </div>
        <?php endif ?>
        <table id="shopping-cart-table" class="cart items data table w-full table-row-items">
            <!-- <caption class="table-caption sm:text-2xl text-xl font-semibold title-font mb-5 text-gray-900 border-b border-b-theme-blue pb-3 text-left">
                <?= $escaper->escapeHtml(__('Shopping Cart Items')) ?>
            </caption> -->
            <thead class="hidden lg:table-header-group border-gray-200 border-b text-md">
                <tr class="text-right">
                    <th class="col item text-left px-7 py-2 text-white bg-black font-semibold" scope="col">
                        <?= $escaper->escapeHtml(__('Item')) ?>
                    </th>
                    <th class="col price px-4 py-2 text-white bg-black font-semibold text-center" scope="col">
                        <?= $escaper->escapeHtml(__('Price')) ?>
                    </th>
                    <th class="col qty px-4 py-2 text-white bg-black font-semibold text-center" scope="col">
                        <?= $escaper->escapeHtml(__('Qty')) ?>
                    </th>
                    <th class="col subtotal px-4 py-2 text-white bg-black font-semibold text-center" scope="col">
                        <?= $escaper->escapeHtml(__('Subtotal')) ?>
                    </th>
                    <th class="col subtotal px-4 py-2 text-white bg-black font-semibold text-center" scope="col">
                        
                    </th>

                </tr>
            </thead>
            <?php foreach ($block->getItems() as $item): ?>
                <?= $block->getItemHtml($item) ?>
            <?php endforeach ?>
        </table>
        <?php if ($block->getPagerHtml()): ?>
            <div class="cart-products-toolbar cart-products-toolbar-bottom toolbar">
                <?= $block->getPagerHtml() ?>
            </div>
        <?php endif ?>
    </div>
    <div class="cart actions flex flex-col sm:flex-row justify-end gap-4 items-center">
        <?php if ($cartViewModel->isClearShoppingCartEnabled()): ?>
        <script>
            function initClearShoppingCartModal() {
                return Object.assign(
                    hyva.modal(),
                    {
                        postData: {
                            action: '<?= $escaper->escapeUrl($block->getUrl('checkout/cart/updatePost')) ?>',
                            data: {update_cart_action: 'empty_cart'}
                        }
                    }
                );
            }
        </script>
            <div x-data="initClearShoppingCartModal()">
                <?= /** @noEscape */ ($confirmation = $modalViewModel
                    ->confirm(__('Are you sure?'))
                    ->withDetails(__('Are you sure you want to remove all items from your shopping cart?'))
                ) ?>
                <button @click="<?= /** @noEscape */ $confirmation->getShowJs() ?>.then(result => result && hyva.postForm(postData))"
                        type="button" title="<?= $escaper->escapeHtmlAttr(__('Clear Shopping Cart')) ?>"
                        class="action clear btn" id="empty_cart_button">
                    <span><?= $escaper->escapeHtml(__('Clear Shopping Cart')) ?></span>
                </button>
            </div>

        <?php endif ?>
        <button type="submit"
                name="update_cart_action"
                data-cart-item-update=""
                value="update_qty"
                title="<?= $escaper->escapeHtmlAttr(__('Update Shopping Cart')) ?>"
                class="action update btn btn-secondary hidden"
        >
            <?= $escaper->escapeHtml(__('Update Shopping Cart')) ?>
        </button>
    </div>
</form>
<?= $block->getChildHtml('checkout.cart.order.actions') ?>
<?= $block->getChildHtml('shopping.cart.table.after') ?>
