<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Magento\Checkout\Block\Cart;
use Magento\Framework\Escaper;

/** @var Cart $block */
/** @var Escaper $escaper */
?>

<div class="flex flex-col flex-col-reverse  lg:flex-row-reverse lg:items-start gap-6 md:gap-8">
    <div class="lg:w-90 xl:w-96 lg:sticky lg:top-[140px]">
        <div class="bg-[#F2F8FF] rounded-[10px] border-b-[6px] border-b-black border border-[#D9D9D9] shadow-lg overflow-hidden">
            <div class="flex flex-col">
                <p class="text-md font-semibold title-font text-left px-4 py-2 text-white bg-black text-white">
                    <?= $escaper->escapeHtml(__('Summary')) ?>
                </p>
            </div>

                <?= $block->getChildHtml('cart.summary') ?>
        </div>
    </div>
    <div class="lg:flex-1 w-full">
        <?= $block->getChildHtml('form_before') ?>
        <?= $block->getChildHtml('cart-items') ?>
        <?= $block->getChildHtml('checkout_cart_widget') ?>
        <?php //$block->getChildHtml('cart.discount') ?>
    </div>
</div>
