<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

/** @var \Magento\Customer\Block\Newsletter $block */
/** @var \Magento\Framework\Escaper $escaper */
?>
<?= $block->getChildHtml('form_before') ?>
    <form class="form form-newsletter-manage bg-white rounded-[10px] border-b-[6px] border-b-black border border-[#D9D9D9] shadow-lg p-5"
          action="<?= $escaper->escapeUrl($block->getAction()) ?>"
          method="post"
          id="form-validate">
        <fieldset class="fieldset">
            <?= $block->getBlockHtml('formkey') ?>
            <div class="text-2xl mb-6">
                <h2 class="mb-5 text-xl block-title">
                    <?= $escaper->escapeHtml(__('Subscription option')) ?>
                </h2>
            </div>
            <div class="field choice flex gap-2">
                <input type="checkbox" name="is_subscribed" id="subscription" value="1"
                       title="<?= $escaper->escapeHtmlAttr(__('General Subscription')) ?>"
                        <?php if ($block->getIsSubscribed()): ?> checked<?php endif; ?>
                       class="checkbox custom-checkbox" />
                <label for="subscription" class="label cursor-pointer select-none mt-1">
                    <span>
                        <?= $escaper->escapeHtml(__('General Subscription')) ?>
                    </span>
                </label>
            </div>
            <?php /* Extensions placeholder */ ?>
            <?= $block->getChildHtml('customer.form.newsletter.extra') ?>
        </fieldset>
        <div class="actions-toolbar">
            <div class="primary-button">
                <button type="submit"
                        title="<?= $escaper->escapeHtmlAttr(__('Save')) ?>"
                        class="action save inline-flex items-center justify-center px-6 py-2 bg-black text-white text-sm md:text-base font-semibold rounded-full hover:bg-theme-blue transition-colors duration-300 "
                >
                    <span>
                        <?= $escaper->escapeHtml(__('Save')) ?>
                    </span>
                </button>
            </div>
            <div class="secondary">
                <a class="action action underline text-black hover:text-theme-blue transition-all duration-300 ease-in-out font-medium text-[0.9rem] md:text-[1rem]"
                   href="<?= $escaper->escapeUrl($block->getBackUrl()) ?>"
                >
                    <span>
                        <?= $escaper->escapeHtml(__('Back')) ?>
                    </span>
                </a>
            </div>
        </div>
    </form>
<?php /* Extensions placeholder */ ?>
<?= $block->getChildHtml('customer.form.newsletter.extra2') ?>
