<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate

/** @var $block \Magento\Sales\Block\Order\Email\Items */
?>
<?php $_order = $block->getOrder() ?>
<?php if ($_order) : ?>
    <?php $_items = $_order->getAllItems(); ?>
    <table border="0" class="email-items" width="100%" style="padding:15px">
        <thead style="background-color:#2c2c34;color:white;">
            <tr>
                <th scope="col" colspan="3" class="item-info" style="text-align:left;font-weight:100;font-size:14px;padding:10px 9px;font-family:'Montserrat',arial,tahoma">
                    <?= $block->escapeHtml(__('Items')) ?>
                </th>

                <!-- Pranav : 17-12-2025 : Start -->
                <th scope="col" class="item-price" style="text-align:center;font-weight:100;font-size:14px;padding:10px 9px;font-family:'Montserrat',arial,tahoma">
                    <?= $block->escapeHtml(__('Price')) ?>
                </th>
                <!-- End -->
              
                <th scope="col" class="item-qty" style="text-align:center;font-weight:100;font-size:14px;padding:10px 9px;font-family:'Montserrat',arial,tahoma">
                    <?= $block->escapeHtml(__('Qty')) ?>
                </th>

                   <th scope="col" class="item-price" style="text-align:right;font-weight:100;font-size:14px;padding:10px 9px;font-family:'Montserrat',arial,tahoma">
                    <?= $block->escapeHtml(__('Price')) ?>
                </th>
              
            </tr>
        </thead>
        <?php foreach ($_items as $_item) : ?>
            <?php if (!$_item->getParentItem()) : ?>
                <tbody>
                    <?= $block->getItemHtml($_item) ?>
                </tbody>
            <?php endif; ?>
        <?php endforeach; ?>
    </table>
    <!-- Pranav : 17-12-2025 : Start -->
    <table width="100%" cellpadding="0" cellspacing="0" style="padding:15px;">
        <tr>
            <td align="right">
                <?= $block->getChildHtml('order_totals') ?>
            </td>
        </tr>
    </table>
    <!-- End -->
    <?php if ($this->helper(\Magento\GiftMessage\Helper\Message::class)
            ->isMessagesAllowed('order', $_order, $_order->getStore())
        && $_order->getGiftMessageId()
    ) : ?>
        <?php $_giftMessage = $this->helper(\Magento\GiftMessage\Helper\Message::class)
            ->getGiftMessage($_order->getGiftMessageId()); ?>
        <?php if ($_giftMessage) : ?>
            <br />
            <table class="message-gift">
                <tr>
                    <td>
                        <h3><?= $block->escapeHtml(__('Gift Message for this Order')) ?></h3>
                        <strong><?= $block->escapeHtml(__('From:')) ?></strong> <?= $block->escapeHtml($_giftMessage->getSender()) ?>
                        <br /><strong><?= $block->escapeHtml(__('To:')) ?></strong> <?= $block->escapeHtml($_giftMessage->getRecipient()) ?>
                        <br /><strong><?= $block->escapeHtml(__('Message:')) ?></strong>
                        <br /><?= $block->escapeHtml($_giftMessage->getMessage()) ?>
                    </td>
                </tr>
            </table>
        <?php endif; ?>
    <?php endif; ?>
<?php endif; ?>
