<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2022-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */
?>
<div class="flex flex-col h-full items-center justify-center text-center space-y-5 py-7 md:py-8">
    <p class="text-lg md:text-2xl">
        <?= $escaper->escapeHtml(__('Please hold on while we take you to complete your payment')) ?>
    </p>
</div>
