<?php $makes = $block->getMakes(); ?>
<form id="vehicle-information-form"
      class="vehicle-information-form"
      x-data="initCheckoutVehicleInfoForm"
      @submit.prevent="submitCheckoutVehicleInfo">
    <div class="grid grid-cols-2 md:grid-cols-4 gap-x-3">
        <div class="mb-3 md:mb-0">
            <div class="vehicle-plate required">
                <label class="label text-black" for="vInfoVehiclePlate"><span><?= __('Vehicle Plate') ?></span></label>
                <div class="control">
                    <input name="vehicle_plate" class="form-input" autocomplete="off"
                           id="vInfoVehiclePlate" type="text"
                           x-ref="plateInput"
                           data-validate='{"required": true}'>
                </div>
            </div>
        </div>
        <div class="mb-3 md:mb-0">
            <div class="make required">
                <label class="label text-black" for="vInfoVehicleMake"><span><?= __('Make') ?></span></label>
                <div class="control">
                    <select id="vInfoVehicleMake" name="vehicle_make"
                            placeholder="Select a person..." autocomplete="off"
                            class="form-select w-full tom-select"
                            x-ref="makeSelect"
                            data-validate='{"required": true}'
                            @change="loadModels">
                        <option value=""><?= __('Select Make') ?></option>
                        <?php foreach ($makes as $make): ?>
                            <option value="<?= $make['value'] ?>"><?= $make['label'] ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
            </div>
        </div>
        <div class="mb-0">
            <div class="model required">
                <label class="label text-black" for="vInfoVehicleModel"><span><?= __('Model') ?></span></label>
                <div class="control">
                    <select id="vInfoVehicleModel" name="vehicle_model"
                            class="form-select w-full tom-select"
                            x-ref="modelSelect"
                            data-validate='{"required": true}'
                            @change="loadYears">
                        <option value=""><?= __('Select Model') ?></option>
                    </select>
                </div>
            </div>
        </div>
        <div class="mb-0">
            <div class="year required">
                <label class="label text-black" for="vInfoVehicleYear"><span><?= __('Year') ?></span></label>
                <div class="">
                    <select id="vInfoVehicleYear" name="vehicle_year"
                            class="form-select w-full tom-select"
                            x-ref="yearSelect"
                            data-validate='{"required": true}'
                            @change="saveYearSelection">
                        <option value=""><?= __('Select Year') ?></option>
                    </select>
                </div>
            </div>
        </div>
    </div>
    <button type="submit" class="hide" id="checkout-vehicleinfo-submit-btn"></button>
</form>
