<?php

/**
 * @category   Hdweb
 * @package    Hdweb_Enquiry
 * @author     vicky.hdit@gmail.com
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace Hdweb\Enquiry\Controller\Ajax;

use Magento\Framework\App\Action\Context;
use Hdweb\Enquiry\Model\EnquiryFactory;
use Magento\Framework\Controller\Result\JsonFactory;
use Magento\Framework\Mail\Template\TransportBuilder;
use Magento\Framework\Translate\Inline\StateInterface;
use Magento\Framework\DataObject;
use Magento\Framework\App\Config\ScopeConfigInterface;
use Magento\Store\Model\ScopeInterface;

class SendEnquiry extends \Magento\Framework\App\Action\Action
{
    /**
     * @var Enquiry
     */
    protected $_enquiry;
    protected $resultJsonFactory;
    protected $transportBuilder;
    protected $inlineTranslation;
    protected $scopeConfig;


    public function __construct(
        Context $context,
        EnquiryFactory $enquiry,
        JsonFactory $resultJsonFactory,
        TransportBuilder $transportBuilder,
        StateInterface $inlineTranslation,
        ScopeConfigInterface $scopeConfig
    ) {
        $this->_enquiry = $enquiry;
        $this->resultJsonFactory = $resultJsonFactory;
        $this->transportBuilder = $transportBuilder;
        $this->inlineTranslation = $inlineTranslation;
        $this->scopeConfig = $scopeConfig;
        parent::__construct($context);
    }
    public function execute()
    {
        $postData = $this->getRequest()->getParams();

        $enquiry = $this->_enquiry->create();
        $enquiry->setName($postData['name']);
        $enquiry->setNumber($postData['number']);
        $enquiry->setEmail($postData['email']);
        $enquiry->setEnquiryFor($postData['service']);
        $enquiry->setMessage($postData['comment']);
        $enquiry->setFormType('Enquiry');
        $enquiry->setStatus(1);
        //$enquiry->setData($data);
        if ($enquiry->save()) {
            $response = ['status' => 'success', 'message' => 'Your inquiry has been sent successfully'];
            $this->sendEmail($postData);
        } else {
            $response = ['status' => 'error', 'message' => 'There was an error sending your inquiry'];
        }
        $resultJson = $this->resultJsonFactory->create();
        return $resultJson->setData($response);
    }

    public function sendEmail($postData)
    {
        $templateOptions = [
            'area' => \Magento\Framework\App\Area::AREA_FRONTEND,
            'store' => \Magento\Store\Model\Store::DEFAULT_STORE_ID,
        ];

        $templateVars = [
            'name' => $postData['name'],
            'number' => $postData['number'],
            'email' => $postData['email'],
            'service' => $postData['service'],
            'comment' => $postData['comment'],
        ];

        $email = $this->scopeConfig->getValue('trans_email/ident_support/email', ScopeInterface::SCOPE_STORE);
        $name  = $this->scopeConfig->getValue('trans_email/ident_support/name', ScopeInterface::SCOPE_STORE);
        $from = array('email' => $email, 'name' => $name);
        $contactSendEmailsTo = $this->scopeConfig->getValue('contact/email/recipient_email', ScopeInterface::SCOPE_STORE);
        if ($contactSendEmailsTo && !empty($contactSendEmailsTo)) {
            $to = [$contactSendEmailsTo];
        } else {
            $to = ['vicky.hdit@gmail.com'];
        }


        //$to = ['vicky.hdit@gmail.com'];
        //$to = ['vicky.hdit@gmail.com','akash.hdit@gmail.com'];
        //$copy_to_bcc = array('nikhil.hdit@gmail.com');
        //$copy_to_cc = 'dhruv.hdit@gmail.com';

        $emailTemplate = $this->scopeConfig->getValue('hdwebemails/email_templates/send_enquiry', ScopeInterface::SCOPE_STORE);

        $this->inlineTranslation->suspend();
        $transport = $this->transportBuilder
            ->setTemplateIdentifier($emailTemplate) // Set your email template identifier
            ->setTemplateOptions($templateOptions)
            ->setTemplateVars($templateVars)
            ->setFrom($from)
            ->addTo($to)
            //->addCc($copy_to_cc)
            //->addBcc($copy_to_bcc)
            ->getTransport();

        $transport->sendMessage();
        $this->inlineTranslation->resume();
    }
}
