<div class="z-50 fixed inset-0 flex justify-center items-center bg-white/70 hidden" id="klever-loader">
    <div class="flex gap-10 items-center p-4">
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 57 57" width="57" height="57" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true">
                            <circle cx="5" cy="50" r="5" style="animation: spinner-ball-triangle1 2.2s linear infinite"></circle>
                            <circle cx="27" cy="5" r="5" style="animation: spinner-ball-triangle2 2.2s linear infinite"></circle>
                            <circle cx="49" cy="50" r="5" style="animation: spinner-ball-triangle3 2.2s linear infinite"></circle>
                        </svg>
                        <span class="text-xl select-none">
                            Loading...                        </span>
                    </div>
</div>
