<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsSolid;
use Hyva\Theme\ViewModel\HyvaCsp;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Escaper $escaper */
/** @var Template $block */
/** @var ViewModelRegistry $viewModels */
/** @var HyvaCsp $hyvaCsp */

/** @var HeroiconsSolid $heroiconsSolid */
$heroiconsSolid = $viewModels->require(HeroiconsSolid::class);
$titlePart1 = (string) $block->getTitlePart1();
$titlePart2 = (string) $block->getTitlePart2();
if ($titlePart1 && $titlePart2) {
    $title = __($titlePart1) . ' <span class="text-theme-blue">' . __($titlePart2) . '</span>';
} else {
    $title = (string) $block->getTitle();
}
$open = (bool) $block->getOpen() ? 'true' : 'false';
$collapseId = 'footer-collapse-' . md5($title);
?>

<?php if ($childrenHtml = $block->getChildHtml()): ?>
    <div
        x-data="footerCollapse(<?= $open === 'true' ? 'true' : 'false' ?>, '<?= $escaper->escapeJs($title) ?>')"
        x-id="['collapse-id']"
        class="border-b border-[#4c4c4c] lg:border-b-0 last:border-b-0 last:mb-[0px] relative mb-[10px] pb-[10px] lg:mb-auto lg:pb-auto h-auto lg:h-full">
        <div
            :id="$id('collapse-id')"
            class="group flex w-full items-center justify-between gap-2 font-bold text-slate-700 lg:pt-0 mb-0 lg:mb-2"
            @click="toggle()"
            @keyup.enter="toggle()"
            @keyup.space="toggle()"
        >
            <span class="font-extrabold text-white text-[1.rem] uppercase mb-0 md:mb-1"><?= /* @noEscape */ $title ?></span>
            <span
                class="transition-transform duration-200 lg:hidden"
                :class="{ 'rotate-180': open }"
                x-ref="toggleIcon"
            >
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="#fff" width="20" height="20" aria-hidden="true">
            <path fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd"></path>
            </svg>
            </span>
        </div>
        <div
            class="overflow-hidden transition-all duration-300 ease-in-out lg:!h-auto lg:block footer-address-content"
            :style="getContentStyle()"
            x-ref="content"
            style="<?= /** @noEscape */ $open === 'true' ? 'height: auto;' : 'height: 0;' ?>"
        >
                <?= /** @noEscape */ $childrenHtml ?>
        </div>
    </div>
<?php endif; ?>
