<section class="google-review bg-black pb-8 pt-8 md:pt-10 lg:pt-16 md:pb-10 lg:pb-16 bg-[position:top_center] md:bg-[position:center_right] bg-cover md:bg-contain bg-no-repeat relative" loading="lazy" style="background-image: url('<?php echo $this->getViewFileUrl('images/home/review-bg.png'); ?>');">
    <div class="absolute inset-0 bg-black/70 md:hidden z-2"></div>
   <div class="container-theme mx-auto z-1">
      <div class="flex flex-wrap items-center w-full justify-center md:justify-start">
         <div class="w-full md:w-3/4 lg:w-3/4 xl:w-2/5">
            <div class="google-review-content">
            <ul class="flex flex-column flex-wrap gap-y-6 md:gap-y-10 lg:gap-y-16">
               <li class="flex text-white relative">
                <i class="icon icon-tyre-simple text-2xl md:text-3xl pt-0"></i>
                <div class="box-info pl-4">
                   <h3 class="font-bold text-[1.4rem] md:text-[1.5rem] lg:text-[1.8rem] xl:text-[1.8rem] 2xl:text-[2rem]"><?php echo __('Fast & Reliable Delivery') ?></h3>
                    <p class="text-[1rem] md:text-[1.1rem] lg:text-[1.5rem] mt-1 md:mt-2"> <span class="block"><?php echo __('Experience Hassle-Free Tire') ?></span> <?php echo __('Installation Right At Your Doorstep.') ?></spanp>
                </div>
                </li>
                 <li class="flex text-white relative">
                <i class="icon icon-tyre-simple text-2xl md:text-3xl pt-0"></i>
                <div class="box-info pl-4">
                   <h3 class="font-bold text-[1.4rem] md:text-[1.5rem] lg:text-[1.8rem] xl:text-[1.8rem] 2xl:text-[2rem]"><?php echo __('Large Tire Inventory') ?></h3>
                    <p class="text-[1rem] md:text-[1.1rem] lg:text-[1.5rem] mt-1 md:mt-2"> <span class="block"><?php echo __('Experience Hassle-Free Tire') ?></span> <?php echo __('Installation Right At Your Doorstep.') ?></spanp>
                </div>
                </li>
            </ul>
            </div>
         </div>
         <div class="w-3/5 md:w-1/4 lg:w-1/4 xl:w-1/5">
            <div class="relative mt-8 md:mt-0">
               <div class="img_wrp w-full pb-full h-0 z-0 pb-[117%] ">
                  <figure class="absolute inset-0">
                     <picture>
                        <source srcset="<?php echo $this->getViewFileUrl('images/home/google-review.png'); ?>" loading="lazy" alt="Google Review" title="Google Review" type="image/jpg">
                        <source srcset="<?php echo $this->getViewFileUrl('images/home/google-review.png'); ?>" loading="lazy" alt="Google Review" title="Google Review" type="image/jpg">
                        <img class="w-full h-full object-cover object-top" src="<?php echo $this->getViewFileUrl('images/home/google-review.png'); ?>" alt="Google Review" loading="lazy">
                     </picture>
                  </figure>
               </div>
            </div>
         </div>
      </div>
   </div>
</section>
