<?php

/**
 * @category   Hdweb
 * @package    Hdweb_Vehicles
 * @author     vicky.hdit@gmail.com
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace Hdweb\Vehicles\Block\Adminhtml\Items\Edit\Tab;

use Magento\Backend\Block\Widget\Form\Generic;
use Magento\Backend\Block\Widget\Tab\TabInterface;
use Magento\Framework\App\DeploymentConfig;
use Magento\Framework\App\Filesystem\DirectoryList;
// use Magento\Framework\App\Config\ScopeConfigInterface;
// use Magento\Store\Model\ScopeInterface;
use Klever\VehicleTyresGuide\Model\ResourceModel\FlatWheelData;

class Main extends Generic implements TabInterface
{
    protected $_wysiwygConfig;
    protected $vehiclesHelper;
    protected $_systemStore;
    protected $_storeManager;
    protected $deploymentConfig;
    protected $directoryList;
    // protected $scopeConfig;
    protected $flatWheelData;

    public function __construct(
        \Magento\Backend\Block\Template\Context $context,
        \Magento\Framework\Registry $registry,
        \Magento\Framework\Data\FormFactory $formFactory,
        \Magento\Cms\Model\Wysiwyg\Config $wysiwygConfig,
        \Hdweb\Vehicles\Helper\Data $vehiclesHelper,
        \Magento\Store\Model\System\Store $systemStore,
        \Magento\Store\Model\StoreManagerInterface $storeManager,
        DeploymentConfig $deploymentConfig,
        DirectoryList $directoryList,
        // ScopeConfigInterface $scopeConfig,
        FlatWheelData $flatWheelData,
        array $data = []
    ) {
        $this->_wysiwygConfig = $wysiwygConfig;
        $this->vehiclesHelper = $vehiclesHelper;
        $this->_systemStore = $systemStore;
        $this->_storeManager = $storeManager;
        $this->deploymentConfig = $deploymentConfig;
        $this->directoryList = $directoryList;
        // $this->scopeConfig = $scopeConfig;
        $this->flatWheelData = $flatWheelData;
        parent::__construct($context, $registry, $formFactory, $data);
    }

    /**
     * {@inheritdoc}
     */
    public function getTabLabel()
    {
        return __('Item Information');
    }

    /**
     * {@inheritdoc}
     */
    public function getTabTitle()
    {
        return __('Item Information');
    }

    /**
     * {@inheritdoc}
     */
    public function canShowTab()
    {
        return true;
    }

    /**
     * {@inheritdoc}
     */
    public function isHidden()
    {
        return false;
    }

    /**
     * Prepare form before rendering HTML
     *
     * @return $this
     * @SuppressWarnings(PHPMD.NPathComplexity)
     * @SuppressWarnings(PHPMD.ExcessiveMethodLength)
     */
    protected function _prepareForm()
    {
        $adminUrl = $this->getBaseUrl() . $this->getAdminPath();
        $model = $this->_coreRegistry->registry('current_hdweb_vehicles_items');
        /** @var \Magento\Framework\Data\Form $form */
        $form = $this->_formFactory->create();
        $form->setHtmlIdPrefix('item_');
        $fieldset = $form->addFieldset('base_fieldset', ['legend' => __('Item Information')]);
        if ($model->getId()) {
            $fieldset->addField('vehicles_id', 'hidden', ['name' => 'vehicles_id']);
        }

        $fieldset->addField(
            'store_id',
            'select',
            [
                'name'     => 'store_id',
                'label'    => __('Store Views'),
                'title'    => __('Store Views'),
                'required' => true,
                'values'   => $this->_systemStore->getStoreValuesForForm(false, true),
            ]
        );

        $fieldset->addField(
            'make',
            'select',
            ['name' => 'make', 'label' => __('Make'), 'title' => __('Make'), 'required' => true, 'values'   => $this->getMakes(), 'onchange' => 'checkSelectedItem(this.value)', 'value' => $model->getMake()]
        )->setAfterElementHtml("
                         <script type=\"text/javascript\">
                            function checkSelectedItem(selectedMake){ 
                               jQuery.ajax( {
                                    url: '" . $adminUrl . "/hdweb_vehicles/items/getmodels',
                                    data: {form_key: window.FORM_KEY,make:selectedMake},
                                    type: 'POST'
                                }).done(function(response) { 
                                    jQuery('.modelSelectField').html(response.response);
                                });
                            }
                         </script>");
        if ($model->getModel()) {
            $modelArray = $this->getModels($model->getMake());
        } else {
            //$modelArray = ["value" => "","label" => __("Select Model")];
            $modelArray = [];
        }
        $fieldset->addField(
            'model',
            'select',
            ['name' => 'model', 'label' => __('Model'), 'title' => __('Model'), 'class' => 'modelSelectField', 'values'   => $modelArray,  'value' => $model->getModel()]
        );

        $fieldset->addField(
            'make_paragraph1',
            'editor',
            [
                'name' => 'make_paragraph1',
                'label' => __('Make Content'),
                'title' => __('Make Content'),
                'style' => 'height:26em;',
                'config'    => $this->_wysiwygConfig->getConfig(),
                'wysiwyg' => true
            ]
        );

        $fieldset->addField(
            'model_paragraph1',
            'editor',
            [
                'name' => 'model_paragraph1',
                'label' => __('Model Content'),
                'title' => __('Model Content'),
                'style' => 'height:26em;',
                'config'    => $this->_wysiwygConfig->getConfig(),
                'wysiwyg' => true
            ]
        );

        /* $fieldset->addField(
            'make_paragraph1',
            'textarea',
            [
                'name' => 'make_paragraph1',
                'label' => __('Make Paragraph 1'),
                'title' => __('Make Paragraph 1'),
            ]
        );

        $fieldset->addField(
            'make_paragraph2',
            'textarea',
            [
                'name' => 'make_paragraph2',
                'label' => __('Make Paragraph 2'),
                'title' => __('Make Paragraph 2'),
            ]
        );

        $fieldset->addField(
            'model_paragraph1',
            'textarea',
            [
                'name' => 'model_paragraph1',
                'label' => __('Model Paragraph 1'),
                'title' => __('Model Paragraph 1'),
            ]
        );

        $fieldset->addField(
            'model_paragraph2',
            'textarea',
            [
                'name' => 'model_paragraph2',
                'label' => __('Model Paragraph 2'),
                'title' => __('Model Paragraph 2'),
            ]
        );

        $fieldset->addField(
            'model_paragraph3',
            'textarea',
            [
                'name' => 'model_paragraph3',
                'label' => __('Model Paragraph 3'),
                'title' => __('Model Paragraph 3'),
            ]
        ); */

        $fieldset->addField(
            'meta_title',
            'text',
            ['name' => 'meta_title', 'label' => __('Meta Title'), 'title' => __('Meta Title')]
        );

        $fieldset->addField(
            'meta_keywords',
            'text',
            ['name' => 'meta_keywords', 'label' => __('Meta Keywords'), 'title' => __('Meta Keywords')]
        );

        $fieldset->addField(
            'meta_description',
            'textarea',
            [
                'name' => 'meta_description',
                'label' => __('Meta Description'),
                'title' => __('Meta Description'),
            ]
        );

        /*$fieldset->addField(
            'status',
            'select',
            ['name' => 'status', 'label' => __('Status'), 'title' => __('Status'),  'options'   => [0 => 'Disable', 1 => 'Enable'], 'required' => true]
        );*/
        /*$fieldset->addField(
            'content',
            'editor',
            [
                'name' => 'content',
                'label' => __('Content'),
                'title' => __('Content'),
                'style' => 'height:26em;',
                'required' => true,
                'config'    => $this->_wysiwygConfig->getConfig(),
                'wysiwyg' => true
            ]
        );*/

        $form->setValues($model->getData());
        $this->setForm($form);
        return parent::_prepareForm();
    }

    public function getMakes()
    {
        // Old: External API call to wheel-size.com
        // $wheelApiKey = $this->scopeConfig->getValue('hdwebapi/general/wheelsize_api_key', ScopeInterface::SCOPE_STORE);
        // $vehicleMakes_url = "https://api.wheel-size.com/v2/makes/?user_key=" . $wheelApiKey . "&region=medm";
        // $vehicleMakes = file_get_contents($vehicleMakes_url);
        // $vehicleMakes = json_decode($vehicleMakes);

        // New: Read from Klever VehicleTyresGuide flat_wheel_data table
        $result = $this->flatWheelData->getMakes(['ordering' => 'name']);
        $options = [];
        $options[] = ["value" => '', "label" => __("Select Make")];
        foreach ($result['rows'] as $value) {
            $options[] = ["value" => $value['slug'], "label" => __($value['name'])];
        }
        return $options;
    }

    public function getModels($make)
    {
        // Old: External API call to wheel-size.com
        // $wheelApiKey = $this->scopeConfig->getValue('hdwebapi/general/wheelsize_api_key', ScopeInterface::SCOPE_STORE);
        // $VehicleModel_url = "https://api.wheel-size.com/v2/models/?user_key=" . $wheelApiKey . "&make=" . $make . "&region=medm";
        // $WheelVehicleModel = file_get_contents($VehicleModel_url);
        // $WheelVehicleModel = json_decode($WheelVehicleModel);

        // New: Read from Klever VehicleTyresGuide flat_wheel_data table
        $result = $this->flatWheelData->getModels($make, ['ordering' => 'name']);
        $options = [];
        $options[] = ["value" => '', "label" => __("Select Model")];
        if (count($result['rows']) > 0) {
            foreach ($result['rows'] as $modelOption) {
                $options[] = ["value" => $modelOption['slug'], "label" => __($modelOption['name'])];
            }
        }

        return $options;
    }

    public function getAdminPath()
    {
        $envFilePath = $this->directoryList->getRoot() . '/app/etc/env.php';

        if (file_exists($envFilePath)) {
            $envConfig = include $envFilePath;
            if (isset($envConfig['backend']['frontName'])) {
                return $envConfig['backend']['frontName'];
            }
        }

        // Default admin path if not found in env.php
        return 'admin';
    }
}
