<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2022-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Hyva\Checkout\ViewModel\Checkout\Formatter as FormatterViewModel;
use Hyva\Theme\Model\ViewModelRegistry;

/** @var Template $block */
/** @var FormatterViewModel $formatterViewModel */
/** @var ViewModelRegistry $viewModels */
/** @var Escaper $escaper */

$formatterViewModel = $viewModels->require(FormatterViewModel::class);
$segment = $block->getSegment();
?>
<div class="flex gap-4 justify-between md:gap-0">
    <span class="label font-bold text-lg text-slate-700">
        <?= $escaper->escapeHtml(array_key_exists('title', $segment)
            ? __($segment['title'])
            : __('Order Total')) ?>
    </span>
    <span class="value font-bold text-right text-slate-700">
        <?php //echo /* @noEscape */ $formatterViewModel->currency($segment['value'] ?? 0) ?>

        <span class="currency-dirham">&#xe900;</span>&nbsp;
        <?= /* @noEscape */ number_format((float)$segment['value'], 2, '.', ',') ?>
    </span>
</div>
