<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2022-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Hyva\Checkout\ViewModel\Checkout\Formatter as FormatterViewModel;
use Hyva\Theme\Model\ViewModelRegistry;

/** @var Template $block */
/** @var FormatterViewModel $formatterViewModel */
/** @var ViewModelRegistry $viewModels */
/** @var Escaper $escaper */

$formatterViewModel = $viewModels->require(FormatterViewModel::class);
$segment = $block->getSegment();
$amount = $segment['value'] ?? 0;
?>
<div class="flex gap-4 justify-between text-slate-800 text-base md:gap-0">
    <span class="label">
        <?= $escaper->escapeHtml(array_key_exists('title', $segment)
            ? __($segment['title'])
            : __('Shipping')) ?>
    </span>
    <span class="value whitespace-nowrap">
        <?php //echo  /* @noEscape */ $formatterViewModel->currencyWithLabelingConditions($segment['value'] ?? 0, 'shipping-total-segment') ?>

        <span class="currency-dirham">&#xe900;</span>&nbsp;
        <?= /* @noEscape */ number_format((float)$amount, 2, '.', ',') ?>
    </span>
</div>
